name: CI
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install
      - run: npm run build
      - run: npm install
      # - run: npm run build:icons

      - name: build icons bi
        working-directory: icons/bi
        run: npm run build

      - name: build icons bs
        working-directory: icons/bs
        run: npm run build

      - name: build icons di
        working-directory: icons/di
        run: npm run build

      - name: build icons sti
        working-directory: icons/sti
        run: npm run build

      - name: build webiste
        working-directory: www
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: ${{ github.event.head_commit.message }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          publish_branch: gh-pages
          publish_dir: ./www/build

      - name: Deploy to icongo.gihub.io Repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # publish_branch: master
          publish_dir: ./www/build
          external_repository: icongo/icongo.gihub.io
